### ISSUE TITLE
Compatibility with dotnet core

### ISSUE THREAD

**Issue by felipecaputo** [DaveSenn/Stomp.Net#1]
Hi @DaveSenn, thanks for the great package. 

I've been using this component in one of my projects, and we want to migrate it to dotnet Core, and I'ld like to know if you are planning to support it.

**Comment by DaveSenn** [comment]
Hi @felipecaputo 

Sorry for the delayed answer. 
Yes I’m planning to add .NETCore support. 

About the time horizon… 
I do not have a lot of time at the moment. 
But I’ve just migrated Extend (Dependency of STOMP.Net)  to .NETCore. So the first task is already done. I hope I can now migrate STOMP.Net quite fast (as soon as I have some spare time) because I’ve some experience from the Extend.

When are you planning to migrate to .NETCore?

Regards Dave

**Comment by felipecaputo** [comment]
Hi @DaveSenn this time it's my turn to apologize for the delayed answer.

We are already migrating some other projects, but there is no deadline yet. So we are expecting to finish this in the next two or three months.

If you would like some help, just tell me and I'll be glad to help.

**Comment by DaveSenn** [comment]
Hi @felipecaputo 

Thanks for the offer. 
I’ve started porting the code (in a different branch _f_core_).

There are three tasks left:
-	Finishing testing
-	Review my workaround for methods which are only available as async in .NETCore.
-	Updating the build script and appveyor config to be compatible with .NETCore

Maybe you can help me with point 1 and 2?

**Testing:**
I’ve updated one of my company’s project to use the new core version. So far everything seems to work, but I’ve not yet finished testing.
Maybe you could replace the DLL in your project as well to check if everything is working for you?

**Async/Sync:**
Microsoft did replace two synchronous methods with async implementations:
- [Dns.GetHostEntry](https://msdn.microsoft.com/en-us/library/ms143998(v=vs.110).aspx)
- [SslStream.AuthenticateAsClient](https://msdn.microsoft.com/en-us/library/system.net.security.sslstream.authenticateasclient(v=vs.110).aspx)

I’m still experimenting to find the best way to “await” these Tasks without creating any deadlocks.
How are you dealing with such async methods in your code?

Here is my current code:
`
return Task.Run( () => Dns.GetHostEntryAsync( host ) )
	.ConfigureAwait( false )
	.GetAwaiter()
	.GetResult();
`

**Comment by felipecaputo** [comment]
Thanks for your feedback @DaveSenn 

About the testing , I'll begin our migration before the end of this week, and we have some automated some E2E tests, and I'll let you know if something breaks.

About the async, I was doing the same way you are, after some research and found lots of people using this same approach.

I'll prioritize this here to help you with tasks 1 and 2 as soon as I can.

Thanks a lot!

**Comment by DaveSenn** [comment]
Thanks for help with the testing.
I’ve updated the build script and the CI configuration.
The first NETCore NuGet package is now published.

**Comment by felipecaputo** [comment]
It's working like a charm.

Thanks a lot!
