### ISSUE TITLE
Definition of "timestamp".

### ISSUE THREAD

**Issue by perl80903** [DaveSenn/Stomp.Net#10]
This is more like a question than an actual issue:

Stomp.Net parses out a property named "timestamp" from incoming messages, if present. 

It is assumed to be an Int64. How is this defined / what does it represent? I can make guesses, but I would like to know its proper definition - I am not finding it in the official STOMP specification.

This field is causing issues for me right now because the other (custom) side that my client talks to provides a date string as the value, e.g. "4/10/2019 8:24:06 AM", which (not surprisingly) causes an exception in StompWireFormat.ReadMessage. 

I would like to inform the authors of the other side that this field has the wrong format, but I need to be able to tell them what the correct one is.

**Comment by TiagoVaccariDA** [comment]
> This is more like a question than an actual issue:
> 
> Stomp.Net parses out a property named "timestamp" from incoming messages, if present.
> 
> It is assumed to be an Int64. How is this defined / what does it represent? I can make guesses, but I would like to know its proper definition - I am not finding it in the official STOMP specification.
> 
> This field is causing issues for me right now because the other (custom) side that my client talks to provides a date string as the value, e.g. "4/10/2019 8:24:06 AM", which (not surprisingly) causes an exception in StompWireFormat.ReadMessage.
> 
> I would like to inform the authors of the other side that this field has the wrong format, but I need to be able to tell them what the correct one is.

Hi perl80903.

I have reviewed that library and definitely it is defined as Int64. It is necessary because the date value was transported possibly using "Unix Timestamp" with milliseconds.

Hope that information was helpful.

**Comment by tvaccari34** [comment]
> This is more like a question than an actual issue:
> 
> Stomp.Net parses out a property named "timestamp" from incoming messages, if present.
> 
> It is assumed to be an Int64. How is this defined / what does it represent? I can make guesses, but I would like to know its proper definition - I am not finding it in the official STOMP specification.
> 
> This field is causing issues for me right now because the other (custom) side that my client talks to provides a date string as the value, e.g. "4/10/2019 8:24:06 AM", which (not surprisingly) causes an exception in StompWireFormat.ReadMessage.
> 
> I would like to inform the authors of the other side that this field has the wrong format, but I need to be able to tell them what the correct one is.

Hi perl80903.

I have reviewed that library and definitely it was defined as Int64. It is necessary because the date value was transported possibly using "Unix Timestamp" with milliseconds.

Hope that information was helpful.

**Comment by DaveSenn** [comment]
Hi @perl80903 

As you may know the library is a modified version of the Apache NMS STOMP library.
The timestamp header was part of the original source code.

If you look at the ActiveMq documentation you can see that the broker understands the timestamp header. 
For example: _Messages also have an optional timestamp which represents the time the message was sent (defined as long)_

I guess the original authors wrote this code with ActiveMq as server in mind …so the added support for the timestamp feature.

The header contains a date-time value as unix time stamp in milliseconds.
In C#: `DateTimeOffset.Now.ToUnixTimeMilliseconds()`

Sorry for my late response… I hope this information is somewhat helpful.

**Comment by perl80903** [comment]
Thanks, Dave, this is exactly what I needed.
