### ISSUE TITLE
Issues in sending messages Asynchronusly

### ISSUE THREAD

**Issue by soumen1102** [DaveSenn/Stomp.Net#8]
When sending messages by turning on the following flags and setting the connection timeout to 0 , AlwaysSyncSend as False, AsyncSend as True , the messages pass through to the Connection.Oneway method but most of them are not received by the Server . The Stomp time to live is set to 30 seconds , any idea what could be going wrong .

I want to send huge number of messages asynchronously , with synchronous approach i can hit upto 1000 messages per second but my requirement is to touch 20K messages / second.

**Comment by DaveSenn** [comment]
AlwaysSyncSend = false and AsyncSend = true will result in the fastest message sending… but sending the message async means that the library will not try to receive any response from the server after sending the message. It could happen that the server returns an error frame, your client would not receive any information about that error (maybe this is the reason for your missing messages).

AsyncSend = false will result in slower message sending but will give you the opportunity to perform some action if the server returns an error frame.

What really improves the performance is to create multiple message producers and send the messages asynchronously on different threads.

I’ve an application which also has to send “huge” amounts of messages as fast as possible.
As part of that application I’ve written a message-sender class which wraps a Stomp.Net session instance and adds producer pooling. 
The class creates a pool of message producers (in my case 20 producers) and exposes a public SendMessage method (thread safe). When ever SendMessage gets invoked a producer will be removed from the pool, used to send the message and then re-added to the pool.
In case no producer is available the method will use SpinWait to wait for a free producer.
The application uses a thread pool thread to call SendMessage for each message it has to send.

With this method I’m able to send 20k messages in 350ms (AsyncSend = true) or 2000ms (AsyncSend = false) and 100k message in 1900ms (AsyncSend = true) or 9600ms (AsyncSend = false) (Tested with Apollo MQ).
