### ISSUE TITLE
Compatability with UWP

### ISSUE THREAD

**Issue by RickdeGier** [DaveSenn/Stomp.Net#9]
I tried to use the example code with an UWP 10.[something] application that connects with ActiveMQ b STOMP broker. But when using underlying code it produces this error.

```
  | Name | Value | Type
-- | -- | -- | --
◢ | InnerException | {System.IO.FileNotFoundException: Could not load file or assembly 
'System.Threading.Thread, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 
The system can not find the given file. 
File name: 'System.Threading.Thread, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'   
 at Stomp.Net.Stomp.Util.IdGenerator..cctor()} | 
System.Exception {System.IO.FileNotFoundException}
```
Code that produces the error:

```
// Create a connection factory
var brokerUri = "tcp://" + Host + ":" + Port;
var conFactory = new ConnectionFactory(brokerUri, new StompConnectionSettings
    {
        UserName = userName,
        Password = Password,
        TransportSettings =
        {
            UseInactivityMonitor = true
        }
    });
IConnection connection = conFactory.CreateConnection(); //ERROR
```

I am trying to implement a connection with ActiveMQ on the HoloLens with Unity so I hope that you can help me.

**Comment by DaveSenn** [comment]
I can reproduce this problem.
Since I never worked with UWP I don’t know match about this application type …but I did some searching.
It appears UWP does not support System.Threading.Thread (at least not with netstandard 1.3), see
https://github.com/dotnet/corefx/issues/2576.
